[package]
name = "dvk"
version = "0.1.0"
authors = ["Vlad Shcherbakov <vlad.shcherbakov@gmail.com>"]
description = "Dynamic loader and definitions for core Vulkan 1.0"
license = "MIT"

[dependencies]
shared_library = "0.1.4"
libc = "0.2.11"
bitflags = "0.7.0"
