[package]
name = "dvk"
version = "0.1.0"
authors = ["Vlad Shcherbakov <vlad.shcherbakov@gmail.com>"]
description = "Dynamic loader and definitions for core Vulkan 1.0"
license = "MIT"

[dependencies]
shared_library = "0.1.4"
libc = "0.2.11"
bitflags = "0.7.0"

[target.'cfg(windows)'.dev-dependencies]
winapi = "0.2.7"
gdi32-sys = "0.2.0"
kernel32-sys = "0.2.2"
user32-sys = "0.2.0"
dvk_khr_surface = { git = "https://gitlab.com/vlsh/dvk_khr_surface.git" }
dvk_khr_win32_surface = { git = "https://gitlab.com/vlsh/dvk_khr_win32_surface.git" }
#bitflags = "0.7.0"
#winapi = "0.2.7"
#gdi32-sys = "0.2.0"
#kernel32-sys = "0.2.2"
#user32-sys = "0.2.0"
#libc = "0.2.11"
#bitflags = "0.7.0"
#advapi32-sys = "0.2.0"
